apiVersion: apps/v1
kind: Deployment
metadata:
  name: ole-cube-core
  labels:
    app: ole-cube-core

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ole-cube-core

  template:
    metadata:
      labels:
        app: ole-cube-core

    spec:
      containers:
      - name: cube

        image: gcr.io/olelifetech/ole-cube-core
        imagePullPolicy: Always

        ports:
        - containerPort: 4000
          name: http

        - containerPort: 15432
          name: sql

        env:

        # API secret para autenticación
        - name: CUBEJS_API_SECRET
          value: "olecubecorepass"

        # Configuración BigQuery
        - name: CUBEJS_DB_TYPE
          value: "bigquery"

        - name: CUBEJS_DB_BQ_PROJECT_ID
          value: "olelifetech"

        # habilita sql api
        - name: CUBEJS_SQL_PORT
          value: "15432"

        # puerto http
        - name: PORT
          value: "4000"

        # modo desarrollo (para ver playground)
        - name: CUBEJS_DEV_MODE
          value: "true"

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"

          limits:
            cpu: "500m"
            memory: "1Gi"